### ISSUE TITLE
Campaign APIs

### ISSUE THREAD

**Issue by quytp** [atubiz/atubiz-service#1]
### Description
* A campaign has these properties
-- `name`
-- `message`
-- `recipients`
-- `companyId`
-- `ownerId`
-- statistic fields including cost, numberOfRecipients, numberOfBlocked, numberOfFaileds, numberOfSent

* A recipient has these properties
-- `firstName`
-- `lastName`
-- `phone`
-- `compaignId`

### APIs
- [x] Create a campaign #2
- [x] Update a campaign #3
- [x] Change status of a campaign #4
- [ ] Import Recipients #5
- [x] Filter Campaigns #6
- [ ] Schedule/Send a campaign #7
- [ ] Add recipients manually #8
- [ ] Delete recipients #9
- [x] Get detail of a campaign #10
- [ ] Get activity log of a campaign #11
- [ ] Cancel a sending campaign #12
