### ISSUE TITLE
User APIs

### ISSUE THREAD

**Issue by quytp** [atubiz/atubiz-service#13]
- [ ] User registration #14 
- [x] User authentication (sign in, sign out) #15
- [x] Get information of a user #22
- [ ] Update information of a user #23
