### ISSUE TITLE
Company APIs

### ISSUE THREAD

**Issue by quytp** [atubiz/atubiz-service#16]
- [x] Create a company #17
- [x] Update information of a company #18 
- [x] Get information of a company #24
- [ ] Invite a member #19
- [ ] Activate/Suspend/Remove a member #20
- [ ] Set role for a member #21
